// Migration service for converting old tracking scripts to Web Pixels

import prisma from "../db.server";
import { generateGooglePixelCode } from "./platforms/google.server";
import { generateMetaPixelCode } from "./platforms/meta.server";
import { generateTikTokPixelCode } from "./platforms/tiktok.server";

export type Platform = "google" | "meta" | "tiktok" | "bing" | "clarity";

export interface MigrationConfig {
  platform: Platform;
  platformId: string;
  additionalConfig?: Record<string, string>;
}

export interface MigrationResult {
  success: boolean;
  platform: Platform;
  pixelCode: string;
  instructions: string[];
  error?: string;
}

// Generate pixel code based on platform
export function generatePixelCode(config: MigrationConfig): MigrationResult {
  try {
    let pixelCode = "";
    let instructions: string[] = [];

    switch (config.platform) {
      case "google":
        pixelCode = generateGooglePixelCode({
          measurementId: config.platformId,
          conversionId: config.additionalConfig?.conversionId,
          conversionLabel: config.additionalConfig?.conversionLabel,
        });
        instructions = [
          "1. 在 Shopify 后台创建新的 Web Pixel",
          "2. 将生成的代码复制到 Web Pixel 编辑器中",
          "3. 保存并发布 Web Pixel",
          "4. 在 Google Ads 中验证转化追踪是否正常",
          "5. 删除旧的 ScriptTag 或 Additional Scripts",
        ];
        break;

      case "meta":
        pixelCode = generateMetaPixelCode({
          pixelId: config.platformId,
        });
        instructions = [
          "1. 在 Shopify 后台创建新的 Web Pixel",
          "2. 将生成的代码复制到 Web Pixel 编辑器中",
          "3. 保存并发布 Web Pixel",
          "4. 在 Meta Events Manager 中验证事件是否正常触发",
          "5. 配置 Conversions API 以提高追踪准确性",
          "6. 删除旧的 ScriptTag 或 Additional Scripts",
        ];
        break;

      case "tiktok":
        pixelCode = generateTikTokPixelCode({
          pixelId: config.platformId,
        });
        instructions = [
          "1. 在 Shopify 后台创建新的 Web Pixel",
          "2. 将生成的代码复制到 Web Pixel 编辑器中",
          "3. 保存并发布 Web Pixel",
          "4. 在 TikTok Events Manager 中验证事件",
          "5. 删除旧的 ScriptTag 或 Additional Scripts",
        ];
        break;

      case "bing":
        pixelCode = generateBingPixelCode({
          tagId: config.platformId,
        });
        instructions = [
          "1. 在 Shopify 后台创建新的 Web Pixel",
          "2. 将生成的代码复制到 Web Pixel 编辑器中",
          "3. 保存并发布 Web Pixel",
          "4. 在 Microsoft Advertising 中验证 UET 标签",
          "5. 删除旧的 ScriptTag 或 Additional Scripts",
        ];
        break;

      case "clarity":
        pixelCode = generateClarityPixelCode({
          projectId: config.platformId,
        });
        instructions = [
          "1. 在 Shopify 后台创建新的 Web Pixel",
          "2. 将生成的代码复制到 Web Pixel 编辑器中",
          "3. 保存并发布 Web Pixel",
          "4. 在 Microsoft Clarity 中验证数据收集",
          "5. 删除旧的 ScriptTag",
        ];
        break;

      default:
        throw new Error(`Unsupported platform: ${config.platform}`);
    }

    return {
      success: true,
      platform: config.platform,
      pixelCode,
      instructions,
    };
  } catch (error) {
    return {
      success: false,
      platform: config.platform,
      pixelCode: "",
      instructions: [],
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

// Save pixel configuration to database
export async function savePixelConfig(
  shopId: string,
  platform: Platform,
  platformId: string,
  credentials?: Record<string, any>
) {
  return prisma.pixelConfig.upsert({
    where: {
      shopId_platform: {
        shopId,
        platform,
      },
    },
    update: {
      platformId,
      credentials: (credentials || undefined) as any,
      migrationStatus: "in_progress",
      updatedAt: new Date(),
    },
    create: {
      shopId,
      platform,
      platformId,
      credentials: (credentials || undefined) as any,
      migrationStatus: "in_progress",
    },
  });
}

// Mark migration as completed
export async function completeMigration(shopId: string, platform: Platform) {
  return prisma.pixelConfig.update({
    where: {
      shopId_platform: {
        shopId,
        platform,
      },
    },
    data: {
      migrationStatus: "completed",
      migratedAt: new Date(),
    },
  });
}

// Get all pixel configs for a shop
export async function getPixelConfigs(shopId: string) {
  return prisma.pixelConfig.findMany({
    where: { shopId },
    orderBy: { createdAt: "desc" },
  });
}

// Microsoft Bing/UET pixel code generator
function generateBingPixelCode(config: { tagId: string }): string {
  return `// Microsoft Advertising UET Tag - Web Pixel Implementation
// Auto-generated by Tracking Guardian

import {register, analytics} from '@shopify/web-pixels-extension';

register(({analytics, browser, settings}) => {
  const UET_TAG_ID = '${config.tagId}';

  // Initialize UET
  (function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:UET_TAG_ID};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");

  // Track page views
  analytics.subscribe('page_viewed', (event) => {
    window.uetq = window.uetq || [];
    window.uetq.push('event', 'page_view', {});
  });

  // Track product views
  analytics.subscribe('product_viewed', (event) => {
    const product = event.data.productVariant;
    window.uetq = window.uetq || [];
    window.uetq.push('event', 'view_item', {
      ecomm_prodid: product.id,
      ecomm_pagetype: 'product',
      revenue_value: parseFloat(product.price.amount),
      currency: product.price.currencyCode,
    });
  });

  // Track add to cart
  analytics.subscribe('product_added_to_cart', (event) => {
    const item = event.data.cartLine;
    window.uetq = window.uetq || [];
    window.uetq.push('event', 'add_to_cart', {
      ecomm_prodid: item.merchandise.id,
      revenue_value: parseFloat(item.merchandise.price.amount) * item.quantity,
      currency: item.merchandise.price.currencyCode,
    });
  });

  // Track checkout started
  analytics.subscribe('checkout_started', (event) => {
    const checkout = event.data.checkout;
    window.uetq = window.uetq || [];
    window.uetq.push('event', 'begin_checkout', {
      revenue_value: parseFloat(checkout.totalPrice.amount),
      currency: checkout.currencyCode,
    });
  });

  // Track purchase
  analytics.subscribe('checkout_completed', (event) => {
    const checkout = event.data.checkout;
    window.uetq = window.uetq || [];
    window.uetq.push('event', 'purchase', {
      revenue_value: parseFloat(checkout.totalPrice.amount),
      currency: checkout.currencyCode,
      transaction_id: checkout.order?.id || checkout.token,
    });
  });
});
`;
}

// Microsoft Clarity pixel code generator
function generateClarityPixelCode(config: { projectId: string }): string {
  return `// Microsoft Clarity - Web Pixel Implementation
// Auto-generated by Tracking Guardian

import {register, analytics} from '@shopify/web-pixels-extension';

register(({analytics, browser, settings}) => {
  const CLARITY_PROJECT_ID = '${config.projectId}';

  // Initialize Clarity
  (function(c,l,a,r,i,t,y){
    c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
    t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
    y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
  })(window, document, "clarity", "script", CLARITY_PROJECT_ID);

  // Clarity automatically tracks page views and user interactions
  // No additional event tracking needed for basic setup

  // Optional: Set custom tags for user segments
  analytics.subscribe('checkout_completed', (event) => {
    const checkout = event.data.checkout;
    if (window.clarity) {
      window.clarity('set', 'purchaser', 'true');
      window.clarity('set', 'order_value', checkout.totalPrice.amount);
    }
  });
});
`;
}

