export const TIMEOUTS = {
    IDLE_CALLBACK: 100,
    SET_TIMEOUT_FALLBACK: 10,
    EXPORT_CLEANUP: 100,
} as const;

export const SAVE_ANALYSIS_LIMITS = {
    MAX_INPUT_SIZE: 1024 * 1024,
    MAX_PLATFORMS: 50,
    MAX_PLATFORM_DETAILS: 200,
    MAX_RISKS: 100,
    MAX_RECOMMENDATIONS: 100,
    MAX_RECOMMENDATION_LENGTH: 500,
    MAX_PLATFORM_NAME_LENGTH: 100,
    MAX_PATTERN_LENGTH: 50,
    MAX_DETECTED_PATTERNS: 20,
    MAX_RISKS_IN_DETAILS: 50,
    MIN_PLATFORM_NAME_LENGTH: 1,
    MIN_RISK_SCORE: 0,
    MAX_RISK_SCORE: 100,
} as const;

export const PLATFORM_NAME_REGEX = /^[a-z0-9_]+$/;
