export { default as prisma } from "../../db.server";

export {

  getShopById,
  getShopIdByDomain,
  getShopWithPixels,
  getShopWithBilling,
  batchGetShops,
  batchGetShopsWithPixels,
  invalidateShopCache,
  invalidateShopCacheByDomain,
  clearShopCaches,
  type ShopBasic,
  type ShopWithPixels,
  type ShopWithBilling,

  getShopPixelConfigs,
  getPixelConfigByPlatform,
  getPixelConfigById,
  getPixelConfigSummaries,
  upsertPixelConfig,
  deactivatePixelConfig,
  deletePixelConfig,
  batchGetPixelConfigs,
  hasServerSideConfigs,
  getConfiguredPlatforms,
  invalidatePixelConfigCache,
  clearPixelConfigCache,
  type PixelConfigCredentials,
  type PixelConfigFull,
  type PixelConfigSummary,
  type PixelConfigInput,

  getPendingJobs,
  claimJobsForProcessing,
  updateJobStatus,
  batchUpdateJobStatus,
  createConversionJob,
  jobExistsForOrder,
  getJobCountsByStatus,
  getDeadLetterJobs,
  requeueDeadLetterJobs,
  cleanupOldJobs,
  type JobForProcessing,
  type QueryPendingJobsOptions,
  type JobStatusUpdate,

  batchCompleteJobs,
  batchInsertReceipts,
  batchUpdateShops,
  executeInTransaction,
  processInChunks,
  type JobCompletionData,
  type PixelReceiptData,
  type BatchResult,

  createAuditLogEntry,
  batchCreateAuditLogs,
  getAuditLogsForShop,
  getAuditLogById,
  cleanupOldAuditLogs,
  countAuditLogsByAction,
  extractRequestContext,
  auditLog,
  createAuditLog,
  type ActorType,
  type AuditAction,
  type ResourceType,
  type AuditLogEntry,
  type AuditLogQueryOptions,
  type AuditLogSummary,
  type AuditLogFull,

  getCachedShop,
  getCachedShopWithConfigs,
  invalidateShopWithConfigsCache,
  getCachedAlertConfigs,
  invalidateAlertConfigsCache,
  getCachedMonthlyUsage,
  invalidateMonthlyUsageCache,
  clearAllCaches,
  getCacheStats,
} from "../../services/db";
