export enum ConnectionIssue {
  INGESTION_SECRET_MISSING = "INGESTION_SECRET_MISSING",
  WEB_PIXEL_NOT_INSTALLED = "WEB_PIXEL_NOT_INSTALLED",
  WEB_PIXEL_MISSING_INGESTION_KEY = "WEB_PIXEL_MISSING_INGESTION_KEY",
  BACKEND_DIAGNOSTIC_ERRORS = "BACKEND_DIAGNOSTIC_ERRORS",
  INGESTION_KEY_ROTATION_IN_PROGRESS = "INGESTION_KEY_ROTATION_IN_PROGRESS",
}
