export enum ConnectionIssue {
  INGESTION_SECRET_MISSING = "INGESTION_SECRET_MISSING",
  WEB_PIXEL_NOT_INSTALLED = "WEB_PIXEL_NOT_INSTALLED",
  WEB_PIXEL_MISSING_INGESTION_KEY = "WEB_PIXEL_MISSING_INGESTION_KEY",
}
